import {
  Banknote,
  Calendar,
  CookingPot,
  FileText,
  Flame,
  Flower2,
  Hand,
  Handshake,
  PawPrint,
  Shirt,
  ShoppingCart,
  Sparkles,
  Star,
  Trash2,
  Turtle,
  Wrench,
  type LucideIcon,
} from 'lucide-react'

export const REACTION_ICONS: Record<string, LucideIcon> = {
  cleaning: Sparkles,
  shopping: ShoppingCart,
  trash: Trash2,
  repair: Wrench,
  paperwork: FileText,
  cooking: CookingPot,
  laundry: Shirt,
  pet: PawPrint,
  payments: Banknote,
  plants: Flower2,
  urgent: Flame,
  important: Star,
  'no-rush': Turtle,
  mine: Hand,
  together: Handshake,
  'this-week': Calendar,
}
